### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by EdisonDelgado** [elaval/Snap4Firstmakers#12]
Cambiar el logotipo de la aplicación, actualmente es muy larga la imagen y se pierde en el menú.

**Comment by pheppk** [comment]
Esperemos a tener el logo definitivo y ahí le ajustamos el tamaño. El logo definitivo debiera estar a fines de diciembre.

**Comment by EdisonDelgado** [comment]
Al eliminar el botón  "cloud" el logo vuelve a la normalidad
