### ISSUE TITLE
Iniciar con lenguaje español y en modo no básico

### ISSUE THREAD

**Issue by pheppk** [elaval/Snap4Firstmakers#13]

**Comment by EdisonDelgado** [comment]
Implementado para la versión 1.0.2

makersGui.js
```Javascript
    if (typeof makersBasicMode == "string" && makersBasicMode) {
        world.isMakersBasicMode = makersBasicMode == "true" ? true : false;
    } else if (typeof makersBasicMode == "boolean") {
        world.isMakersBasicMode = makersBasicMode
    } else {
        world.isMakersBasicMode = false;  //default 
    }
    if (typeof makersV2 !== "undefined" && makersV2) {
        world.isMakersV2 = makersV2 == "true" ? true : false;
    } else if (typeof makersV2 == "boolean") {
        world.isMakersV2 = isMakersV2;
    } else {
        world.isMakersV2 = false; // default
    }
    
    //Init in spanish
    if (language && language !== 'es') {
        this.userLanguage = language;
    } else {
        this.userLanguage = 'es'//default;
    }
```

**Comment by elaval** [comment]
Dejé esta "nueva funcionalidad" para la v1.1.0 (la próxima que saquemos con nuevas funcionalidades).   Las otras nuevas funcionalidades la dejé para "el futuro" yen la medida que Pedro decida la siguiente prioridad la asigna a la v1.2.0. 

Propongo dejar la 1.0.2 para corregir errores urgentes asociados a la versión actual.

**Comment by EdisonDelgado** [comment]
Esto ya está listo pero aún no se ha subido el nuevo código al repositorio. ¿Lo vamos cerrando de inmediato o esperamos a probarlo en el próximo release?

**Comment by elaval** [comment]
Una vez que hagas el commit y lo subas (después de probarlo), puedes cerrar
el issue.

Incluso hay una manera de cerrar automáticamente el issue ci en el
comentario del commit incluyes "(fix #4)" - como ejemplo para cerrar el
issue #4.

Ernesto

2015-12-02 19:48 GMT+00:00 Edison Delgado A. <notifications@github.com>:

**Comment by pheppk** [comment]
Supongo que antes de cerrar un issue le revisan todos los comentarios -- yo agregué alguno recién.
