### ISSUE TITLE
Menu (en Mac) dice nwjs en vez de Snap4Firtmakers

### ISSUE THREAD

**Issue by elaval** [elaval/Snap4Firstmakers#14]

**Comment by elaval** [comment]
La barra de menu de la Aplicación (al lado del menú de la manzana) no está correcta

**Comment by EdisonDelgado** [comment]
Implementado para la versión 1.0.2.
Se modifica y se agrega el nombre "Snap4Firstmakers" en el archivo Info.plist de paquete ejecutable en mac.
