### ISSUE TITLE
Traducciones faltantes

### ISSUE THREAD

**Issue by EdisonDelgado** [elaval/Snap4Firstmakers#15]
Faltan traducciones al español en las categorías de bloques y menús.

**Comment by pheppk** [comment]
Ojo que en el menú de archivos, dice "New Arduino translatable project" -- eliminar o traducir.

**Comment by pheppk** [comment]
Quedan algunas traducciones en lugares remotos!.

Al hacer clic en el botón derecho del disfraz de un sprite ofrece opciones en inglés (pen: tip, middle)
Al pasar el ratón sobre el la bromista en el disfraz, indica el tooltip: "Paint a new costume"
