### ISSUE TITLE
Simplificar "abrir" y "guardar" vs. "importar" y "exportar"

### ISSUE THREAD

**Issue by pheppk** [elaval/Snap4Firstmakers#17]
Entiendo que esto queda del Snap que opera sobre un browser, pero en nuestro caso, en que el software se trabaja como desktop, me parece más simple olvidarnos de la nube (sacando el ícono de la nube y sus funciones) y usar el mismo sistema de archivos tradicional: abrir y guardar en el sistema de archivos del computador.

**Comment by pheppk** [comment]
Funciona correcto en Mac. Pone extension .xml al guardar y abre bien posteriormente.

**Comment by EdisonDelgado** [comment]
Solucionado!
