### ISSUE TITLE
Problemas con cargar ejemplos del menú de Archivos

### ISSUE THREAD

**Issue by pheppk** [elaval/Snap4Firstmakers#18]
Al cargar ejemplos del menú de Archivos, indica que son de una versión anterior y la interfaz queda corrupta (en el escenario, en particular con un ejemplo).

**Comment by EdisonDelgado** [comment]
Como los proyectos se crearon con la versión anterior da un error al importar, debemos volver a crear los XML con la nueva versión. Ya se implementaron ejemplos básicos (-blink-) a medida que avancemos podemos incorporar más.
