### ISSUE TITLE
Agregar ventana emergente cuando se desconecta la tarjeta

### ISSUE THREAD

**Issue by mpasmino** [elaval/Snap4Firstmakers#20]
Se podría agregar una ventana emergente cuando se desconecta la tarjeta, como cuando se cambia de versión, o se carga un nuevo ejemplo.

**Comment by EdisonDelgado** [comment]
Si se despliega, por alguna razón en windows se demora más en aparecer.Puede que sea problema del plugin del puerto serial que no comunica a tiempo el evento 'disconnect'.

**Comment by EdisonDelgado** [comment]
Solucionado en la versión 1.0.3
