### ISSUE TITLE
Ajuste del lenguaje

### ISSUE THREAD

**Issue by pheppk** [elaval/Snap4Firstmakers#21]
En los disfraces, hay una explicación que se refiere a buscar una foto desde el "ordenador". Sugiero usar "computador".

**Comment by EdisonDelgado** [comment]
![captura de pantalla 2015-12-14 a las 3 19 46 p m](https://cloud.githubusercontent.com/assets/1309328/11789625/3052e556-a276-11e5-87bd-1feefcd88e6a.png)
Corregido!
